version: '3.8'

services:
  wiki:
    build: .
    ports:
      - "21313:21313"
    volumes:
      # Mount a volume for persistent data storage
      - wiki-data:/app/files
      - wiki-pages:/app/persistence
      # Direct host mapping for development
      - /var/www/wiki/persistence:/app/persistence

volumes:
  wiki-data:
  wiki-pages: 