version: '3.8'

services:
  wiki:
    build: .
    ports:
      - "21313:21313"
    volumes:
      # Mount a volume for persistent data storage
      - wiki-data:/app/files
      - wiki-pages:/app/persistent
      # Direct host mapping for development
      - /var/www/wiki/files:/app/persistent

volumes:
  wiki-data:
  wiki-pages: 